package com.quant.finance.execution.enums;

public enum BotCommand {
  POSITIONS, PNL, PNL_SINGLE, START_ACCOUNT_SUMMARY, STOP_ACCOUNT_SUMMARY, START_ACCOUNT_UPDATES,
  STOP_ACCOUNT_UPDATES, BUY, SELL, CLOSE_ALL, OPEN_ORDERS, CANCEL_ORDER, CANCEL_OPEN_ORDERS, UNKNOWN
}
