package com.quant.finance.execution.enums;

public enum BotCommand {
  POSITIONS, SYNC_POSITIONS, PNL, CANCEL_PNL, PNL_SINGLE, BUY, SELL, CLOSE_ALL,
  START_ACCOUNT_SUMMARY,
  STOP_ACCOUNT_SUMMARY,
  START_ACCOUNT_UPDATES, STOP_ACCOUNT_UPDATES, OPEN_ORDERS, CANCEL_ORDER, CANCEL_OPEN_ORDERS,
  RESTART_ENGINE, STOP_ENGINE, START_ENGINE,
  UNKNOWN
}
