project: quant

spring:
  application:
    name: ExecutionEngine

application:
  client:
    discord:
      url: 'https://discord.com'
    telegram:
      url: 'https://api.telegram.org'
      token: '8068983143:AAGyxjjqig8ZJAjBFuxdg8Obwy-Y41OKCdA'
      chatId: '1014578999'