server:
    port: 8081
logging:
    level:
        ROOT: INFO
        com.quant.finance.execution: INFO

spring:
    application:
        name: ExecutionEngine
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/quant
        username: ${QUANT_ENGINE_USER}
        password: ${QUANT_ENGINE_PASSWORD}
    jpa:
        open-in-view: false
        show-sql: false
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                default_schema: engine
    liquibase:
        enabled: true
        change-log: classpath:/changelog/master.yaml

application:
    client:
        telegram:
            url: 'https://api.telegram.org'
            token: '8068983143:AAGyxjjqig8ZJAjBFuxdg8Obwy-Y41OKCdA'
            chatId: '1014578999'
            botUsername: TradingViewAletsBot
            enabled: false
        gateway:
            host: 128.140.74.222
            port: 7497
            id: 2
    contract:
        count: 1
    account:
        id: DU8704817